apiVersion: v1
kind: Secret
metadata:
  name: bmc-node2-credentials
  namespace: default
type: Opaque
stringData:
  username: ${BMC_NODE2_USERNAME}
  password: ${BMC_NODE2_PASSWORD}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: basic-longhorn-cp-node2
  namespace: default
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMACAddress: ${NODE2_MAC_BOOT}
  bmc:
    address: ${BMC_NODE2_ADDRESS}
    credentialsName: bmc-node2-credentials
  automatedCleaningMode: disabled
