apiVersion: v1
kind: Secret
metadata:
  name: bmc-node3-credentials
  namespace: default
type: Opaque
stringData:
  username: ${BMC_NODE3_USERNAME}
  password: ${BMC_NODE3_PASSWORD}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: basic-longhorn-cp-node3
  namespace: default
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMACAddress: ${NODE3_MAC_BOOT}
  bmc:
    address: ${BMC_NODE3_ADDRESS}
    credentialsName: bmc-node3-credentials
  automatedCleaningMode: disabled
