apiVersion: v1
kind: Secret
metadata:
  name: bmc-node1-credentials
  namespace: default
type: Opaque
stringData:
  username: ${BMC_NODE1_USERNAME}
  password: ${BMC_NODE1_PASSWORD}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: basic-longhorn-cp-node1
  namespace: default
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMACAddress: ${BMC_NODE1_MAC}
  bmc:
    address: ${BMC_NODE1_ADDRESS}
    credentialsName: bmc-node1-credentials
  automatedCleaningMode: disabled
